### ISSUE TITLE
Provision on WiFi

### ISSUE THREAD

**Issue by agherzan** [resin-os/resin-ts#1]
# Description

Provision device using a WiFi device.
# Steps to reproduce issue

Download Device OS
Network Connection: Wifi
Download OS file
# Expected result

Device should appear in the application's dashboard
# Actual result

Missing wireless firmware
# Other information

Reported by: Theodor Gherzan 

Test configuration: TS7700 

Test case number: TC02 

Test run: [https://resinio.testlodge.com/projects/16238/runs/192879?tab=2&run_section_id=168774&executed_case_id=9333875#executed_case_9333875](https://resinio.testlodge.com/projects/16238/runs/192879?tab=2&run_section_id=168774&executed_case_id=9333875#executed_case_9333875)

**Comment by agherzan** [comment]
Duplicate of #12

**Comment by floion** [comment]
We need @telphan to say if it really is a duplicate
