### ISSUE TITLE
Provision on WiFi

### ISSUE THREAD

**Issue by agherzan** [resin-os/resin-ts#12]
# Description

Provision device using a WiFi device.
# Steps to reproduce issue

Download Device OS
Network Connection: Wifi
Download OS file
# Expected result

Device should appear in the application's dashboard
# Actual result

On the quad core variant:

root@ts-imx6:~# [   17.363792] wlan0: authenticate with ae:9e:17:e9:f9:5d
[   17.405139] wlan0: send auth to ae:9e:17:e9:f9:5d (try 1/3)
[   17.413696] wlan0: authenticated
[   17.419933] wlan0: deauthenticating from ae:9e:17:e9:f9:5d by local choice (reason=3)
[   17.427882] wlan0: associate with ae:9e:17:e9:f9:5d (try 1/3)
[   17.441023] wlan0: RX AssocResp from ae:9e:17:e9:f9:5d (capab=0x1411 status=0 aid=1)
[   17.458247] wlan0: associated
[   17.461272] IPv6: ADDRCONF(NETDEV_CHANGE): wlan0: link becomes ready
[   17.499793] wlan0: deauthenticating from ae:9e:17:e9:f9:5d by local choice (reason=3)
[   17.563077] cfg80211: Calling CRDA to update world regulatory domain
[   17.584585] cfg80211: World regulatory domain updated:
[   17.589743] cfg80211:  DFS Master region: unset
[   17.594105] cfg80211:   (start_freq - end_freq @ bandwidth), (max_antenna_gain, max_eirp)
[   17.605614] cfg80211:   (2402000 KHz - 2472000 KHz @ 40000 KHz), (N/A, 2000 mBm)
[   17.613037] cfg80211:   (2457000 KHz - 2482000 KHz @ 40000 KHz), (N/A, 2000 mBm)
[   17.622844] cfg80211:   (2474000 KHz - 2494000 KHz @ 20000 KHz), (N/A, 2000 mBm)
i[   17.631810] cfg80211:   (5170000 KHz - 5250000 KHz @ 80000 KHz), (N/A, 2000 mBm)
[   17.640461] cfg80211:   (5250000 KHz - 5330000 KHz @ 80000 KHz), (N/A, 2000 mBm)
[   17.648931] cfg80211:   (5490000 KHz - 5730000 KHz @ 160000 KHz), (N/A, 2000 mBm)
[   17.657566] cfg80211:   (5735000 KHz - 5835000 KHz @ 80000 KHz), (N/A, 2000 mBm)
[   17.666656] cfg80211:   (57240000 KHz - 63720000 KHz @ 2160000 KHz), (N/A, 0 mBm)
fco[   18.130179] wlan0: authenticate with ae:9e:17:e9:f9:5d
[   18.184866] wlan0: send auth to ae:9e:17:e9:f9:5d (try 1/3)
[   18.205404] wlan0: send auth to ae:9e:17:e9:f9:5d (try 2/3)
[   18.221422] wlan0: send auth to ae:9e:17:e9:f9:5d (try 3/3)
[   18.237742] wlan0: authentication with ae:9e:17:e9:f9:5d timed out
# Other information

Reported by: Florin Sarbu 

Test configuration: TS4900 

Test case number: TC02 

Test run: [https://resinio.testlodge.com/projects/16238/runs/210416?tab=2&run_section_id=205774&executed_case_id=9973913#executed_case_9973913](https://resinio.testlodge.com/projects/16238/runs/210416?tab=2&run_section_id=205774&executed_case_id=9973913#executed_case_9973913)

**Comment by telphan** [comment]
The use of an antenna really renders this bug obsolete.

**Comment by agherzan** [comment]
In this case we can close this issue. Thanks @telphan
