### ISSUE TITLE
[TS7700] Docker 1.10 fails to start

### ISSUE THREAD

**Issue by telphan** [resin-os/resin-ts#29]
Please refer to this: https://github.com/docker/docker/issues/24315.

**Comment by telphan** [comment]
@floion @agherzan 
[strace_7700.txt](https://github.com/resin-os/resin-ts/files/349578/strace_7700.txt)
[strace_rpi.txt](https://github.com/resin-os/resin-ts/files/349589/strace_rpi.txt)

**Comment by agherzan** [comment]
Currently blocked until @lorenzo-stoakes gets a board.

**Comment by ljskernel** [comment]
Resolved by https://github.com/boltdb/bolt/pull/578 am working on PR'ing a patch for this.

**Comment by ljskernel** [comment]
Moved to https://github.com/resin-os/meta-resin/issues/227
